/**
 * Curated subset of unDraw slugs with titles for AI to choose from.
 * Kept small to limit token usage. Full list: undraw-svg illustrations.json
 */
const STICKER_SLUGS: { slug: string; title: string }[] = [
  { slug: "teamwork", title: "Teamwork" },
  { slug: "programming", title: "Programming" },
  { slug: "love-messages", title: "Love Messages" },
  { slug: "document-ready", title: "Document Ready" },
  { slug: "add-to-cart", title: "Add to Cart" },
  { slug: "online-meeting", title: "Online Meeting" },
  { slug: "problem-solving", title: "Problem Solving" },
  { slug: "analytics-setup", title: "Analytics Setup" },
  { slug: "random-thoughts", title: "Random Thoughts" },
  { slug: "overly-proud", title: "Overly Proud" },
  { slug: "travel-booking", title: "Travel Booking" },
  { slug: "continuous-learning", title: "Continuous Learning" },
  { slug: "weather-forecast", title: "Weather Forecast" },
  { slug: "product-demo", title: "Product Demo" },
  { slug: "thought-process", title: "Thought Process" },
  { slug: "mindfulness", title: "Mindfulness" },
  { slug: "researching", title: "Researching" },
  { slug: "key-insights", title: "Key Insights" },
  { slug: "eating-together", title: "Eating Together" },
  { slug: "social-update", title: "Social Update" },
  { slug: "customer-survey", title: "Customer Survey" },
  { slug: "loading-ui", title: "Loading UI" },
  { slug: "money-received", title: "Money Received" },
  { slug: "connection-lost", title: "Connection Lost" },
  { slug: "newsfeed", title: "Newsfeed" },
  { slug: "personal-finance", title: "Personal Finance" },
  { slug: "presentation", title: "Presentation" },
  { slug: "true-friends", title: "True Friends" },
  { slug: "online-meetings", title: "Online Meetings" },
  { slug: "working-at-home", title: "Working at Home" },
  { slug: "ai-answers", title: "AI Answers" },
  { slug: "virtual-reality", title: "Virtual Reality" },
  { slug: "code-review", title: "Code Review" },
  { slug: "texting", title: "Texting" },
  { slug: "business-call", title: "Business Call" },
  { slug: "confident", title: "Confident" },
  { slug: "maintenance", title: "Maintenance" },
  { slug: "send-money", title: "Send Money" },
  { slug: "sharing-knowledge", title: "Sharing Knowledge" },
  { slug: "homework-research", title: "Homework Research" },
  { slug: "customize-app", title: "Customize App" },
  { slug: "watering-plants", title: "Watering Plants" },
  { slug: "online-profile", title: "Online Profile" },
  { slug: "online-stats", title: "Online Stats" },
  { slug: "unlock", title: "Unlock" },
  { slug: "sign-here", title: "Sign Here" },
  { slug: "sports-scores", title: "Sports Scores" },
  { slug: "color-palette", title: "Color Palette" },
  { slug: "referral", title: "Referral" },
  { slug: "capture-the-moment", title: "Capture the Moment" },
  { slug: "completing", title: "Completing" },
  { slug: "ai-response", title: "AI Response" },
  { slug: "adjust-settings", title: "Adjust Settings" },
  { slug: "authentication", title: "Authentication" },
  { slug: "real-time-collaboration", title: "Real-time Collaboration" },
  { slug: "add-files", title: "Add Files" },
  { slug: "add-notes", title: "Add Notes" },
  { slug: "adventure", title: "Adventure" },
  { slug: "celebration", title: "Celebration" },
];

export function getStickerSlugs(): string {
  return JSON.stringify(
    STICKER_SLUGS.map(({ slug, title }) => ({ slug, title })),
    null,
    0,
  );
}
